
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Δημήτρης
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form admin
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpdialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        close = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        info = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        arrow = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        information = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        info2 = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();

        helpdialog.setTitle("About");
        helpdialog.setAlwaysOnTop(true);
        helpdialog.setResizable(false);
        helpdialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 110));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-garage-door-part-open-100 (1).png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-under-construction-40.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 50, 70));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 180, 350));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n   Η Εφαρμόγη αυτη υλοποιήθικε στα  \nπλαίσια του μαθήματος Αλληλεπίδραση \nΑνθρώπου & Υπολογίστη \n\n Απο τους \n  • Μαρία Πάππα\n  • Χρήστος Πέιος   \n  • Δημήτρης Γεωργίου\n\n\n\t\t\t11/2020");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 540, 390));

        helpdialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 340));

        close.setAlwaysOnTop(true);
        close.setLocation(new java.awt.Point(320, 130));
        close.setMinimumSize(new java.awt.Dimension(320, 130));
        close.setResizable(false);
        close.setSize(new java.awt.Dimension(320, 130));
        close.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Οχι");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, 30));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Θέλετε να γίνει έξοδος;");
        close.getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 20));

        jButton2.setText("Ναι");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data");
        setLocation(new java.awt.Point(400, 80));
        setMaximumSize(new java.awt.Dimension(812, 709));
        setMinimumSize(new java.awt.Dimension(812, 709));
        setPreferredSize(new java.awt.Dimension(812, 709));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(850, 650));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Αποθήκευση");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 390, 130, 30));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refresh.png"))); // NOI18N
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 40, 40));

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Αριθμός Πινακίδας", "Ονοματεπώνυμο", "Τηλέφωνο", "Τύπος Οχήματος", "Πλύσιμο", "Συνολικός Χρόνος"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setColumnSelectionAllowed(true);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(jTable2);
        jTable2.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        for (int i=0;i<home.table.length;i++){
            Calendar calstop = Calendar.getInstance(); //Με την εντολή παίρνουμε την ώρα του συστήματος σε Milliseconds
            home.time[i][1]=calstop.getTimeInMillis();//OraTelous
            home.time[i][2]=((home.time[i][1]-home.time[i][0])/1000);
            if (home.table[i][0]!=null){
                Object[] rowtable={home.table[i][0],home.table[i][1],home.table[i][2],home.table[i][3],home.table[i][4],home.time[i][2]};
                DefaultTableModel modeltable=(DefaultTableModel) jTable2.getModel();
                modeltable.addRow(rowtable);
            }
        }
        updatejTable2RowHeights();

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 710, 270));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Πίνακας Table[][]");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 650, 44));

        info.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        info.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        info.setText("Πληροφορίες");
        jPanel1.add(info, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 800, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 800, 30));
        jLabel5.setText("To parking δέχεται έως και "+home.xoretikotita+" θέσεις.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 800, 30));
        jLabel4.setText("Συνολικά εισερχόμενα αυτοκίνητα :"+home.metritis+" ");

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow-50.png"))); // NOI18N
        arrow.setAutoscrolls(true);
        arrow.setBorderPainted(false);
        arrow.setContentAreaFilled(false);
        arrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrow.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        arrow.setSelected(true);
        arrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowActionPerformed(evt);
            }
        });
        jPanel1.add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 71, 72));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 140, 90));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 130));

        jPanel5.setBackground(new java.awt.Color(0, 0, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 800, 130));

        information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-information-50.png"))); // NOI18N
        information.setBorderPainted(false);
        information.setContentAreaFilled(false);
        information.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationActionPerformed(evt);
            }
        });
        jPanel1.add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 580, 70, 70));

        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("HH:mm:ss");
        String formattedDate = myDateObj.format(myFormatObj);
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Ανανεώθηκε στις : "+formattedDate);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 300, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 660));

        jMenu1.setText("Αρχείο");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu1MouseReleased(evt);
            }
        });

        jMenuItem3.setText("Έξοδος");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        info2.setText("Πληροφορίες");
        info2.setEnabled(false);
        info2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                info2MousePressed(evt);
            }
        });

        admin.setText("Διαχειριστής");
        admin.setEnabled(false);
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        info2.add(admin);

        jMenuBar1.add(info2);

        help.setText("Σχετικά με");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMousePressed(evt);
            }
        });
        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowActionPerformed
        dispose();
        home next =new home();
        next.setVisible(true);
    }//GEN-LAST:event_arrowActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
    JFileChooser fileChooser = new JFileChooser();
    fileChooser.setDialogTitle("Save");
    fileChooser.setCurrentDirectory(new File ("."));
    fileChooser.setToolTipText(".txt");
    LocalDateTime myDateObj = LocalDateTime.now();
    DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
    String formattedDate = myDateObj.format(myFormatObj);
    int userselection=fileChooser.showSaveDialog(this);
    if (userselection==JFileChooser.APPROVE_OPTION){
        File fileToSave = fileChooser.getSelectedFile();
        try {
            FileWriter fw =new FileWriter(fileToSave+".txt");
            BufferedWriter bw =new BufferedWriter(fw);
            bw.write("------------------------------START-----------------------------\n");
            for (int i=0;i<jTable2.getRowCount();i++){
                bw.write("------------------------------"+(i+1)+"------------------------------\n");
                for (int j=0;j<jTable2.getColumnCount();j++){
                    if (j==0){
                        bw.write("Αριθμός Πινακίδας : "+jTable2.getValueAt(i,j).toString());
                    }
                    else if (j==1){
                        bw.write("Ονοματεπώνυμο : "+jTable2.getValueAt(i,j).toString());

                    }
                    else if (j==2){
                        bw.write("Τηλέφωνο Επικοινωνίας : "+jTable2.getValueAt(i,j).toString());
                    }
                    else if (j==3){
                        bw.write("Τύπος  : "+jTable2.getValueAt(i,j).toString());
                    
                    }
                    else if(j==4){
                        bw.write("Πλύσιμο  : "+jTable2.getValueAt(i,j).toString());
                    }
                    else if(j==5){
                        bw.write("Συνολικός Χρόνος στάθμευσης  : "+jTable2.getValueAt(i,j).toString());
                    }
                    bw.newLine();
                }
            }
            bw.write("\n\n****************Date&Time : "+formattedDate+"****************\n------------------------------END------------------------------");
            JOptionPane.showMessageDialog(this,"SUCCESFULLY LOADED","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
            bw.close();
            fw.close();
        }catch(IOException ex){
            JOptionPane.showMessageDialog(this,"ERROR","ERROR MESSAGE",JOptionPane.ERROR_MESSAGE);
        }
    
        
    }    }//GEN-LAST:event_jButton3MousePressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    //Clear Table
    
        DefaultTableModel dm = (DefaultTableModel) jTable2.getModel();
        dm.getDataVector().removeAllElements();
        revalidate();
    //Fill Table
        
    for (int i=0;i<home.table.length;i++){
    Calendar calstop = Calendar.getInstance(); //Με την εντολή παίρνουμε την ώρα του συστήματος σε Milliseconds
    home.time[i][1]=calstop.getTimeInMillis();//OraTelous
    home.time[i][2]=((home.time[i][1]-home.time[i][0])/1000);            
    if (home.table[i][0]!=null){
        Object[] rowtable={home.table[i][0],home.table[i][1],home.table[i][2],home.table[i][3],home.table[i][4],home.time[i][2]};
        DefaultTableModel modeltable=(DefaultTableModel) jTable2.getModel();
        modeltable.addRow(rowtable);   
    }
}
LocalDateTime myDateObj = LocalDateTime.now();
DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("HH:mm:ss");
String formattedDate = myDateObj.format(myFormatObj);
jLabel3.setText("Ανανεώθηκε στις : "+formattedDate);
updatejTable2RowHeights();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationActionPerformed
        dispose();
        info next =new info();
        next.setVisible(true);
    }//GEN-LAST:event_informationActionPerformed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        close.setVisible(true);
        close.setLocation(650,400);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseReleased

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked

    }//GEN-LAST:event_adminMouseClicked

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
        dispose();
        admin next =new admin();
        next.setVisible(true);
    }//GEN-LAST:event_adminMousePressed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void info2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info2MouseClicked

    }//GEN-LAST:event_info2MouseClicked

    private void info2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info2MousePressed

    }//GEN-LAST:event_info2MousePressed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseClicked

    private void helpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMousePressed
        helpdialog.setVisible(true);
        helpdialog.setVisible(true);
        helpdialog.setSize(690,375);
        helpdialog.setLocation(450,300);

    }//GEN-LAST:event_helpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admin;
    private javax.swing.JButton arrow;
    private javax.swing.JDialog close;
    private javax.swing.JMenu help;
    private javax.swing.JDialog helpdialog;
    private javax.swing.JLabel info;
    private javax.swing.JMenu info2;
    private javax.swing.JButton information;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
private void updatejTable2RowHeights(){
    for (int row = 0; row < jTable2.getRowCount(); row++)
    {
        int rowHeight = jTable2.getRowHeight();

        for (int column = 0; column < jTable2.getColumnCount(); column++)
        {
            Component comp = jTable2.prepareRenderer(jTable2.getCellRenderer(row, column), row, column);
            rowHeight = Math.max(rowHeight, comp.getPreferredSize().height);
        }

        jTable2.setRowHeight(row, rowHeight);
    }
}
}
