
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Timer;
import java.util.TimerTask;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Δημήτρης
 */
public class enter extends javax.swing.JFrame {

    /**
     * Creates new form enter
     */
    public enter() {
        initComponents();

        //upobolh.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpdialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        close = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        good = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        arrow = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        arpi = new javax.swing.JTextField();
        onep = new javax.swing.JTextField();
        thlefonoepikoinonias = new javax.swing.JLabel();
        arithmospinakidas = new javax.swing.JLabel();
        thlep = new javax.swing.JTextField();
        upobolh = new javax.swing.JButton();
        tipos = new javax.swing.JComboBox<>(home.tupos);
        jLabel1 = new javax.swing.JLabel();
        onomateponumo = new javax.swing.JLabel();
        button_label = new javax.swing.JLabel();
        button_label1 = new javax.swing.JLabel();
        wash = new javax.swing.JCheckBox();
        agree = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        information = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        info = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();

        helpdialog.setTitle("About");
        helpdialog.setAlwaysOnTop(true);
        helpdialog.setResizable(false);
        helpdialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 110));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-garage-door-part-open-100 (1).png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-under-construction-40.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 50, 70));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 180, 350));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n   Η Εφαρμόγη αυτη υλοποιήθικε στα  \nπλαίσια του μαθήματος Αλληλεπίδραση \nΑνθρώπου & Υπολογίστη \n\n Απο τους \n  • Μαρία Πάππα\n  • Χρήστος Πέιος   \n  • Δημήτρης Γεωργίου\n\n\n\t\t\t11/2020");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 540, 390));

        helpdialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 340));

        close.setAlwaysOnTop(true);
        close.setLocation(new java.awt.Point(320, 130));
        close.setMinimumSize(new java.awt.Dimension(320, 130));
        close.setResizable(false);
        close.setSize(new java.awt.Dimension(320, 130));
        close.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Οχι");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Θέλετε να γίνει έξοδος;");
        close.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 20));

        jButton2.setText("Ναι");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 30));

        good.setAlwaysOnTop(true);
        good.setMinimumSize(new java.awt.Dimension(690, 375));
        good.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 102, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 100, 110));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 200));

        jButton3.setBackground(new java.awt.Color(100, 255, 100));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, 80));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Καθημερινά 24 ώρες!");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 370, 20));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ΠΛΗΡΟΦΟΡΙΕΣ");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 390, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Στοιχεία Επικοινωνίας:");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 390, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Διεύθυνση: Κολοκοτρώνη 15, Θεσσαλονίκη");
        jLabel8.setToolTipText("");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 390, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Τηλέφωνο: 2310 550550");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 380, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("e-mail: info@parking.gr");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 380, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Επιτυχής Καταχώρηση !!");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 710, 40));

        javax.swing.GroupLayout goodLayout = new javax.swing.GroupLayout(good.getContentPane());
        good.getContentPane().setLayout(goodLayout);
        goodLayout.setHorizontalGroup(
            goodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
            .addGroup(goodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(goodLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        goodLayout.setVerticalGroup(
            goodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(goodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(goodLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setLocation(new java.awt.Point(400, 80));
        setMinimumSize(new java.awt.Dimension(812, 709));
        setPreferredSize(new java.awt.Dimension(812, 709));
        setResizable(false);
        setSize(new java.awt.Dimension(812, 709));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-forest-60.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 69));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-garage-door-part-open-100 (1).png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 88, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-under-construction-40.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 40, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow-50.png"))); // NOI18N
        arrow.setAutoscrolls(true);
        arrow.setBorderPainted(false);
        arrow.setContentAreaFilled(false);
        arrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrow.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        arrow.setSelected(true);
        arrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowActionPerformed(evt);
            }
        });
        jPanel1.add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 71, 72));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 810, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("*Με Λατινικούς Χαρακτήρες");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 240, 20));

        arpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arpiActionPerformed(evt);
            }
        });
        arpi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arpiKeyReleased(evt);
            }
        });
        jPanel2.add(arpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 240, 30));

        onep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onepActionPerformed(evt);
            }
        });
        onep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                onepKeyReleased(evt);
            }
        });
        jPanel2.add(onep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 240, 30));

        thlefonoepikoinonias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        thlefonoepikoinonias.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        thlefonoepikoinonias.setText("ΤΗΛΕΦΩΝΟ ΕΠΙΚΟΙΝΩΝΙΑΣ :");
        jPanel2.add(thlefonoepikoinonias, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 260, 30));

        arithmospinakidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        arithmospinakidas.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        arithmospinakidas.setText("ΑΡΙΘΜΟΣ ΠΙΝΑΚΙΔΑΣ :");
        jPanel2.add(arithmospinakidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 260, 30));

        thlep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thlepActionPerformed(evt);
            }
        });
        thlep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                thlepKeyReleased(evt);
            }
        });
        jPanel2.add(thlep, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 240, 30));

        upobolh.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        upobolh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upobolh.png"))); // NOI18N
        upobolh.setBorderPainted(false);
        upobolh.setContentAreaFilled(false);
        upobolh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upobolh.setFocusPainted(false);
        upobolh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upobolhActionPerformed(evt);
            }
        });
        jPanel2.add(upobolh, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 100, 50));

        tipos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tiposActionPerformed(evt);
            }
        });
        jPanel2.add(tipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 430, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ΣΥΜΠΛΗΡΩΣΤΕ ΤΑ ΣΤΟΙΧΕΙΑ ΣΑΣ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 610, 40));

        onomateponumo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        onomateponumo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        onomateponumo.setText("ΟΝΟΜΑΤΕΠΩΝΥΜΟ :");
        jPanel2.add(onomateponumo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 260, 30));

        button_label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_label.setForeground(new java.awt.Color(255, 51, 51));
        button_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(button_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 800, 40));

        button_label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_label1.setForeground(new java.awt.Color(0, 0, 255));
        button_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(button_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 800, 40));

        wash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        wash.setText("Πλύσιμο");
        wash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washActionPerformed(evt);
            }
        });
        jPanel2.add(wash, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 90, 40));

        agree.setText("Δέχομαι  τους Όρους & Προϋποθέσεις");
        agree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agreeActionPerformed(evt);
            }
        });
        jPanel2.add(agree, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 300, -1));

        jLabel5.setText("*Με Λατινικούς Χαρακτήρες");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 240, 20));

        information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-information-50.png"))); // NOI18N
        information.setBorderPainted(false);
        information.setContentAreaFilled(false);
        information.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 310, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 257, 800, 400));

        jMenu1.setText("Αρχείο");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu1MouseReleased(evt);
            }
        });

        jMenuItem3.setText("Έξοδος");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        info.setText("Πληροφορίες");
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMousePressed(evt);
            }
        });

        admin.setText("Διαχειριστής");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        info.add(admin);

        jMenuBar1.add(info);

        help.setText("Σχετικά με");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMousePressed(evt);
            }
        });
        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowActionPerformed
        dispose();
        home next =new home();
        next.setVisible(true);

    }//GEN-LAST:event_arrowActionPerformed

    private void arpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arpiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arpiActionPerformed

    private void onepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onepActionPerformed

    private void thlepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thlepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thlepActionPerformed
  
    
    private void upobolhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upobolhActionPerformed
       //STart
        
        
        int findpositive=-1,k=0;
        button_label1.setText("");
        button_label.setText("");
        boolean test=false;
        boolean exist=false;
        do {
            if (home.table[k][0]==null){
                test=true;
                findpositive=k;
            }
            k++;           
        }while(!(k>home.table.length-1 || test));
        if (test){
            home.kataxoritis=findpositive;
        }
        //STOP
        String phone = thlep.getText();
        Pattern patternthlep = Pattern.compile("^\\d{10}$");//Tilephono
        Matcher matcherthlep = patternthlep.matcher(phone);
        
       String pin = arpi.getText();
       Pattern patternarpi = Pattern.compile("^[a|A|b|B|e|E|z|Z|h|H|i|I|k|K|m|M|n|N|o|O|p|P|t|T|y|Y|x|X]{3}-\\d{4}");//Arithmos pinakidas
       if (home.tupos[tipos.getSelectedIndex()].equals("Μηχανή")){
            patternarpi = Pattern.compile("^[a|A|b|B|e|E|z|Z|h|H|i|I|k|K|m|M|n|N|o|O|p|P|t|T|y|Y|x|X]{3}-\\d{1,3}");//Arithmos pinakidas
        }
       else if (home.tupos[tipos.getSelectedIndex()].equals("Άλλο")){
           patternarpi = Pattern.compile("^[a|A|b|B|e|E|z|Z|h|H|i|I|k|K|m|M|n|N|o|O|p|P|t|T|y|Y|x|X]{1,}-\\d{1,}");//Arithmos pinakidas
        }
         
                   
        
        Matcher matcharpi = patternarpi.matcher(pin); 
        String name=onep.getText();
        Pattern patternname = Pattern.compile("^[[a-z]|[A-Z]]{2,}[ ]{1}[[a-z]|[A-Z]]{2,}$");//Tilephono
        Matcher matchertname = patternname.matcher(name);
        for (int i=0;i<=home.table.length-1;i++){
            if (home.table[i][0]!=null){
                if (home.table[i][0].equalsIgnoreCase(arpi.getText()))
                {
                    exist=true;
                }
            }
        }
        if (agree.isSelected()){
            if (test && !exist){  
                if (matchertname.matches()) {
                     if (matcharpi.matches()) {
                         if (matcherthlep.matches()) {
                             home.table[home.kataxoritis][2]=thlep.getText();//Thlephono
                             home.table[home.kataxoritis][0]=arpi.getText();
                             home.table[home.kataxoritis][1]=onep.getText();
                             home.table[home.kataxoritis][2]=thlep.getText();
                             home.table[home.kataxoritis][3]=home.tupos[tipos.getSelectedIndex()];

                             Calendar calstart = Calendar.getInstance(); //Με την εντολή παίρνουμε την ώρα του συστήματος σε Milliseconds

                             home.time[home.kataxoritis][0]=calstart.getTimeInMillis();//[0] Γτ είναι start time 
                             if (wash.isSelected()){
                                 home.table[home.kataxoritis][4]="Ναι";// 4 επειδη ειναι wash
                             }
                             else{
                                 home.table[home.kataxoritis][4]="Όχι";
                             }
                             button_label.setText("Σας ευχαριστούμε!");
                             home.metritis++;
                             home.kataxoritis++;
                            LocalDateTime myDateObj = LocalDateTime.now();
                            DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
                            String formattedDate = myDateObj.format(myFormatObj);
                            System.out.println("Το όχημα με Αριθμο Κυκλόφωριας : "+arpi.getText()+"\t Μπήκε στις : "+formattedDate);
                            good.setVisible(true);
                            good.setLocation(450,300);
                         }
                         else{
                             button_label.setText("Δώστε ένα έγκυρο τηλέφωνο");
                             button_label1.setText("<10 ψηφία> ή <Κωδικός χώρας (πχ +30)> <τον αριθμό>");
                         }      
                     }
                     else{
                         if (home.tupos[tipos.getSelectedIndex()].equals("Αυτοκίνητο")){
                               button_label.setText("Δώστε τον Αριθμό Πινακίδας");
                               button_label1.setText("Αυτοκίνητο XXX-AAAA");

                         }
                         else if (home.tupos[tipos.getSelectedIndex()].equals("Μηχανή")){
                             button_label.setText("Δώστε τον Αριθμό Πινακίδας");
                             button_label1.setText("Μηχανή : XXX-AAA ή ΧΧΧ-ΑΑ ή ΧΧΧ-Α ");

                         }
                         else //Allo
                         { 
                             button_label1.setText("Χρησιμοποιήστε λατινικούς χαρακτήρες");
                         }
                     }
                 }
                 else{
                 button_label.setText("Δώστε ένα εγκύρο Ονοματεπώνυμο");
                 button_label1.setText("Της μορφής : Όνομα <κενό> Επίθετο");
                 }
            }   
            else if (!test){
                button_label.setText("Δυστυχώς το parking είναι γεμάτο. Σας ευχαριστούμε !");
            }
            else if(exist){
                button_label.setText("To όχημα υπάρχει στο parking");
            }
        }
        else
        {
            button_label.setText("Επιλέξτε δέχομαι τους  Όρους & Προυποθέσεις");

        }
        
           
     
        
    }//GEN-LAST:event_upobolhActionPerformed

    private void onepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_onepKeyReleased
      //  upobolh.setEnabled(false);

    }//GEN-LAST:event_onepKeyReleased

    private void thlepKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_thlepKeyReleased
       //upobolh.setEnabled(false);
    }//GEN-LAST:event_thlepKeyReleased

    private void arpiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arpiKeyReleased
      //  upobolh.setEnabled(true);
    }//GEN-LAST:event_arpiKeyReleased

    private void washActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washActionPerformed
       
    }//GEN-LAST:event_washActionPerformed

    private void tiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tiposActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tiposActionPerformed

    private void agreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agreeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agreeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        good.setVisible(false);
        dispose();
        home next =new home();
        next.setVisible(true);

    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        close.setVisible(true);
        close.setLocation(650,400);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseReleased

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked

    }//GEN-LAST:event_adminMouseClicked

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
        dispose();
        admin next =new admin();
        next.setVisible(true);
    }//GEN-LAST:event_adminMousePressed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked

    }//GEN-LAST:event_infoMouseClicked

    private void infoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMousePressed

    }//GEN-LAST:event_infoMousePressed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseClicked

    private void helpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMousePressed
        helpdialog.setVisible(true);
        helpdialog.setVisible(true);
        helpdialog.setSize(690,375);
        helpdialog.setLocation(450,300);

    }//GEN-LAST:event_helpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void enter() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(enter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new enter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admin;
    private javax.swing.JCheckBox agree;
    private javax.swing.JLabel arithmospinakidas;
    private javax.swing.JTextField arpi;
    private javax.swing.JButton arrow;
    private javax.swing.JLabel button_label;
    private javax.swing.JLabel button_label1;
    private javax.swing.JDialog close;
    private javax.swing.JDialog good;
    private javax.swing.JMenu help;
    private javax.swing.JDialog helpdialog;
    private javax.swing.JMenu info;
    private javax.swing.JButton information;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField onep;
    private javax.swing.JLabel onomateponumo;
    private javax.swing.JLabel thlefonoepikoinonias;
    private javax.swing.JTextField thlep;
    private javax.swing.JComboBox<String> tipos;
    private javax.swing.JButton upobolh;
    private javax.swing.JCheckBox wash;
    // End of variables declaration//GEN-END:variables

    
static void scan(int a){
    System.out.print("Input seconds => : ");
    String secs;
    secs=String.valueOf(a);
    int delay = 1000;
    int period = 1000;
    timer = new Timer();
    interval = Integer.parseInt(secs);
    System.out.println(secs);
    timer.scheduleAtFixedRate(new TimerTask() {

        public void run() {
            String a1=String.valueOf(setInterval());
            System.out.println(a1);
           
        }
    }, delay, period);
}
 static int interval;
static Timer timer;
private static final int setInterval() {
    if (interval == 1)
        timer.cancel();
        
    return --interval;
}
}

