
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Δημήτρης
 */
          
public class exit extends javax.swing.JFrame {
    /**
     * Creates new form exit
     */
  
    public exit() {
        initComponents();
        //lathos.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpdialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        close = new javax.swing.JDialog();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ak = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();
        yourphone = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        yourname = new javax.swing.JLabel();
        yourtype = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        Find = new javax.swing.JButton();
        Sosta = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        button_label1 = new javax.swing.JLabel();
        information = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        arrow = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        info = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();

        helpdialog.setTitle("About");
        helpdialog.setAlwaysOnTop(true);
        helpdialog.setResizable(false);
        helpdialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 110));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-garage-door-part-open-100 (1).png"))); // NOI18N
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-under-construction-40.png"))); // NOI18N
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 50, 70));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 180, 350));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n   Η Εφαρμόγη αυτη υλοποιήθικε στα  \nπλαίσια του μαθήματος Αλληλεπίδραση \nΑνθρώπου & Υπολογίστη \n\n Απο τους \n  • Μαρία Πάππα\n  • Χρήστος Πέιος   \n  • Δημήτρης Γεωργίου\n\n\n\t\t\t11/2020");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 540, 390));

        helpdialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 340));

        close.setAlwaysOnTop(true);
        close.setLocation(new java.awt.Point(320, 130));
        close.setMinimumSize(new java.awt.Dimension(320, 130));
        close.setResizable(false);
        close.setSize(new java.awt.Dimension(320, 130));
        close.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Οχι");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Θέλετε να γίνει έξοδος;");
        close.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 20));

        jButton2.setText("Ναι");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Find my car");
        setLocation(new java.awt.Point(400, 80));
        setMaximumSize(new java.awt.Dimension(812, 709));
        setMinimumSize(new java.awt.Dimension(812, 709));
        setPreferredSize(new java.awt.Dimension(812, 709));
        setResizable(false);
        setSize(new java.awt.Dimension(812, 709));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akActionPerformed(evt);
            }
        });
        ak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                akKeyReleased(evt);
            }
        });
        jPanel2.add(ak, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 230, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("ΑΡΙΘΜΟΣ ΠΙΝΑΚΙΔΑΣ :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ΣΥΜΠΛΗΡΩΣΤΕ ΤΑ ΣΤΟΙΧΕΙΑ ΣΑΣ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 570, 40));

        fail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fail.setForeground(new java.awt.Color(204, 0, 51));
        fail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(fail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 730, 30));

        yourphone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yourphone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(yourphone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 260, 30));

        name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 260, 30));

        yourname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yourname.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(yourname, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 260, 30));

        yourtype.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        yourtype.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(yourtype, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 260, 30));

        phone.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 30));

        type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        type.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jPanel2.add(type, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 260, 30));

        Find.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Find.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/find.png"))); // NOI18N
        Find.setBorderPainted(false);
        Find.setContentAreaFilled(false);
        Find.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Find.setFocusPainted(false);
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        jPanel2.add(Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 270, 60));

        Sosta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Sosta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/swsta.png"))); // NOI18N
        Sosta.setBorderPainted(false);
        Sosta.setContentAreaFilled(false);
        Sosta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Sosta.setEnabled(false);
        Sosta.setFocusPainted(false);
        Sosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SostaActionPerformed(evt);
            }
        });
        jPanel2.add(Sosta, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 120, 60));

        jLabel6.setText("*Με Λατινικούς Χαρακτήρες");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 240, 20));

        button_label1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        button_label1.setForeground(new java.awt.Color(0, 0, 255));
        button_label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(button_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 730, 30));

        information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-information-50.png"))); // NOI18N
        information.setBorderPainted(false);
        information.setContentAreaFilled(false);
        information.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationActionPerformed(evt);
            }
        });
        jPanel2.add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 800, 380));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-forest-60.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 69));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-garage-door-part-open-100 (1).png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-under-construction-40.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow-50.png"))); // NOI18N
        arrow.setAutoscrolls(true);
        arrow.setBorderPainted(false);
        arrow.setContentAreaFilled(false);
        arrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrow.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        arrow.setSelected(true);
        arrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowActionPerformed(evt);
            }
        });
        jPanel1.add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 71, 72));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 810, 270));

        jMenu1.setText("Αρχείο");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu1MouseReleased(evt);
            }
        });

        jMenuItem3.setText("Έξοδος");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        info.setText("Πληροφορίες");
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMousePressed(evt);
            }
        });

        admin.setText("Διαχειριστής");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        info.add(admin);

        jMenuBar1.add(info);

        help.setText("Σχετικά με");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMousePressed(evt);
            }
        });
        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void arrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowActionPerformed
       dispose();
        home next =new home();
        next.setVisible(true);

    }//GEN-LAST:event_arrowActionPerformed

    private void akActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akActionPerformed
    }//GEN-LAST:event_akActionPerformed
    static int thesi=-1;
    static int finalcost;
    private void akKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_akKeyReleased
     //  lathos.setEnabled(true);
    }//GEN-LAST:event_akKeyReleased

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
    //Ψχνω το αυτοκινητο και εμφανιζω στοιχεια
    thesi=-1;
    button_label1.setText("");
    fail.setText("");
    String check=ak.getText();
    Pattern pattern = Pattern.compile("^[a|A|b|B|e|E|z|Z|h|H|i|I|k|K|m|M|n|N|o|O|p|P|t|T|y|Y|x|X]{1,}-\\d{1,}");
    Matcher matchern = pattern.matcher(check);
    if (matchern.matches())
    {
        for (int i=0;i<=home.table.length-1;i++)
        {   
            if (home.table[i][0]!=null){
                if (home.table[i][0].equalsIgnoreCase(check)) 
                {
                    thesi=i;
                }
            }
        }
        if (exit.thesi!=-1)
        {
            Sosta.setEnabled(true);
            name.setText("Όνομα");
            phone.setText("Τηλέφωνο");            
            type.setText("Τύπος Οχήματος");

            yourname.setText(home.table[thesi][1]);
            yourphone.setText(home.table[thesi][2]);
            yourtype.setText(home.table[thesi][3]);
                        
            Calendar calstop = Calendar.getInstance(); //Με την εντολή παίρνουμε την ώρα του συστήματος σε Milliseconds
            home.time[thesi][1]=calstop.getTimeInMillis();//OraTelous
            home.time[thesi][2]=((home.time[thesi][1]-home.time[thesi][0])/1000);//Sinolikos Xronos Sthathmeusis se sec
            
           
              
            int sinxronos=(int)(home.time[thesi][2]);
            //Ypologismos Kostous
            if (sinxronos<=180) //>3λεπτά
            {       //Kato apo 3λεπτά
                if (sinxronos<=30)
                {//30δευτερολεπτα
                    finalcost=0;
                }
                else if (sinxronos<=60)
                {           //1hour
                    finalcost=4;
                }
                else if ((sinxronos>=60))
                {
                    finalcost=6;
                }
            }
            else
            {
             finalcost=((1*((sinxronos-180)/60))+6);
            if (finalcost==6){
                finalcost=finalcost+1;
            }     
            }
            if (home.table[thesi][4]=="Ναι")
            {
                finalcost=finalcost+2;
            }           
        }
        else
        {
            fail.setText("Το αυτοκίνητό σας δεν είναι καταχωρημένο");
            Sosta.setEnabled(false);
            ak.setText("");
            
            name.setText("");
            phone.setText("");
            type.setText("");
            yourname.setText("");
            yourphone.setText("");
            yourtype.setText("");
         }  
    } 
    else
    {
        button_label1.setText("<Γράματα>-<Αριθμοί>");
        fail.setText("Παρακαλώ γράψτε έναν έγκυρό αριθμό πινακίδας");
        Sosta.setEnabled(false); 
        name.setText("");
        phone.setText("");     
        type.setText("");
        yourname.setText("");
        yourphone.setText("");
        yourtype.setText("");
    }
        
    }//GEN-LAST:event_FindActionPerformed
    private void SostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SostaActionPerformed
        pliromi next =new pliromi();
        next.setVisible(true);
        dispose();
    }//GEN-LAST:event_SostaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        close.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationActionPerformed
        dispose();
        info next =new info();
        next.setVisible(true); 
    }//GEN-LAST:event_informationActionPerformed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        close.setVisible(true);
        close.setLocation(650,400);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseReleased

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked

    }//GEN-LAST:event_adminMouseClicked

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
        dispose();
        admin next =new admin();
        next.setVisible(true);
    }//GEN-LAST:event_adminMousePressed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked

    }//GEN-LAST:event_infoMouseClicked

    private void infoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMousePressed

    }//GEN-LAST:event_infoMousePressed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseClicked

    private void helpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMousePressed
        helpdialog.setVisible(true);
        helpdialog.setVisible(true);
        helpdialog.setSize(690,375);
        helpdialog.setLocation(450,300);

    }//GEN-LAST:event_helpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void exit() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(exit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new exit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Find;
    private javax.swing.JButton Sosta;
    private javax.swing.JMenuItem admin;
    private javax.swing.JTextField ak;
    private javax.swing.JButton arrow;
    private javax.swing.JLabel button_label1;
    private javax.swing.JDialog close;
    private javax.swing.JLabel fail;
    private javax.swing.JMenu help;
    private javax.swing.JDialog helpdialog;
    private javax.swing.JMenu info;
    private javax.swing.JButton information;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel name;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel type;
    private javax.swing.JLabel yourname;
    private javax.swing.JLabel yourphone;
    private javax.swing.JLabel yourtype;
    // End of variables declaration//GEN-END:variables
}
