
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Δημήτρης
 */
public class pliromi extends javax.swing.JFrame {

    /**
     * Creates new form pliromi
     */
    public pliromi() {
        initComponents();
    }
    private static DecimalFormat df2 = new DecimalFormat("#.##");


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        helpdialog = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        thankyou = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        close = new javax.swing.JDialog();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        arrow = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        pay = new javax.swing.JButton();
        response = new javax.swing.JLabel();
        information = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        extra = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        akfinded = new javax.swing.JLabel();
        userverify = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        verify = new javax.swing.JLabel();
        verify12 = new javax.swing.JLabel();
        verify1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        info = new javax.swing.JMenu();
        admin = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();

        helpdialog.setTitle("About");
        helpdialog.setAlwaysOnTop(true);
        helpdialog.setMinimumSize(new java.awt.Dimension(690, 375));
        helpdialog.setResizable(false);
        helpdialog.setSize(new java.awt.Dimension(690, 375));
        helpdialog.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(51, 102, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 100, 110));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-garage-door-part-open-100 (1).png"))); // NOI18N
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 80));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-under-construction-40.png"))); // NOI18N
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 50, 70));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 180, 350));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 2, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setText("\n\n   Η Εφαρμόγη αυτη υλοποιήθικε στα  \nπλαίσια του μαθήματος Αλληλεπίδραση \nΑνθρώπου & Υπολογίστη \n\n Απο τους \n  • Μαρία Πάππα\n  • Χρήστος Πέικος   \n  • Δημήτρης Γεωργίου\n\n\n\t\t\t11/2020");
        jScrollPane2.setViewportView(jTextArea2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, -10, 540, 390));

        helpdialog.getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 340));

        thankyou.setTitle("Thank you ");
        thankyou.setAlwaysOnTop(true);
        thankyou.setBackground(new java.awt.Color(255, 255, 255));
        thankyou.setMinimumSize(new java.awt.Dimension(690, 375));
        thankyou.setModal(true);
        thankyou.setResizable(false);
        thankyou.setSize(new java.awt.Dimension(710, 428));
        thankyou.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(51, 102, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel11.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 100, 110));

        jPanel5.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 200));

        jButton3.setBackground(new java.awt.Color(100, 255, 100));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 90, 70));

        jLabel28.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Καθημερινά 24 ώρες!");
        jPanel5.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 370, 20));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ΠΛΗΡΟΦΟΡΙΕΣ");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 390, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Στοιχεία Επικοινωνίας:");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 390, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Διεύθυνση: Κολοκοτρώνη 15, Θεσσαλονίκη");
        jLabel5.setToolTipText("");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 390, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Τηλέφωνο: 2310 550550");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 380, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("e-mail: info@parking.gr");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 380, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Καλό ταξίδι !");
        jPanel5.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 710, 50));

        thankyou.getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 430));

        close.setAlwaysOnTop(true);
        close.setAutoRequestFocus(false);
        close.setLocation(new java.awt.Point(320, 130));
        close.setMinimumSize(new java.awt.Dimension(320, 130));
        close.setResizable(false);
        close.setSize(new java.awt.Dimension(320, 130));
        close.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setText("Οχι");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Θέλετε να γίνει έξοδος;");
        close.getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 320, 20));

        jButton2.setText("Ναι");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        close.getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 70, 30));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pay");
        setLocation(new java.awt.Point(400, 80));
        setMaximumSize(new java.awt.Dimension(812, 709));
        setMinimumSize(new java.awt.Dimension(812, 709));
        setPreferredSize(new java.awt.Dimension(812, 709));
        setResizable(false);
        setSize(new java.awt.Dimension(812, 709));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-forest-60.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, -1, 69));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-garage-door-part-open-100 (1).png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, -1));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-under-construction-40.png"))); // NOI18N
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/parking.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        arrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arrow-50.png"))); // NOI18N
        arrow.setAutoscrolls(true);
        arrow.setBorderPainted(false);
        arrow.setContentAreaFilled(false);
        arrow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        arrow.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        arrow.setSelected(true);
        arrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrowActionPerformed(evt);
            }
        });
        jPanel2.add(arrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 71, 72));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 810, 270));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pay.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pay.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/plhrvmh.png"))); // NOI18N
        pay.setBorderPainted(false);
        pay.setEnabled(true);
        pay.setContentAreaFilled(false);
        pay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pay.setFocusPainted(false);
        pay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payActionPerformed(evt);
            }
        });
        jPanel3.add(pay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 160, 60));

        response.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        response.setForeground(new java.awt.Color(255, 0, 0));
        response.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(response, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 580, 50));

        information.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-information-50.png"))); // NOI18N
        information.setBorderPainted(false);
        information.setContentAreaFilled(false);
        information.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        information.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informationActionPerformed(evt);
            }
        });
        jPanel3.add(information, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 320, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("ΠΛΥΣΙΜΟ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel7.setText("ΚΟΣΤΟΣ");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 270, 30));

        cost.setFont(new java.awt.Font("Tahoma", 0, 14));
        String test1=String.valueOf(exit.finalcost);
        cost.setText(test1);
        cost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(cost, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 230, 30));

        extra.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        String test3=String.valueOf(home.table[exit.thesi][4]);
        extra.setText(test3);
        extra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(extra, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, 230, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("ΣΥΝΟΛΙΚΟΣ ΧΡΟΝΟΣ ΣΤΑΘΜΕΥΣΗΣ");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 280, 40));

        time2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        time2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        double test21=Double.valueOf((home.time[exit.thesi][2])/60);
        df2.setRoundingMode(RoundingMode.UP);
        time2.setText(df2.format(test21)+": Λεπτά");
        jPanel3.add(time2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 230, 30));

        akfinded.setFont(new java.awt.Font("Tahoma", 1, 14));
        String test=String.valueOf(home.table[exit.thesi][0]);
        akfinded.setText(test);
        jPanel3.add(akfinded, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 100, 40));

        userverify.setVisible(false);
        userverify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userverifyActionPerformed(evt);
            }
        });
        jPanel3.add(userverify, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 140, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Παρακαλώ εισάγετε τον κωδικό επιβεβαίωσης");
        jLabel9.setVisible(false);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 410, 80));

        jButton1.setVisible(false);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/upobolh.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 100, 50));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Αποτελέσματα για οχήμα με Αριθμό Κυκλοφορίας :");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 570, 40));

        verify.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        verify.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        verify.setVisible(false);
        verify.setText("Κωδικός Επιβεβαίωσης");
        jPanel3.add(verify, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 250, 50));

        verify12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel3.add(verify12, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 210, 40));

        String pin=String.valueOf((int)((Math.random() * 10000) + 0));
        verify1.setVisible(false);
        verify1.setText(pin);
        jPanel3.add(verify1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 120, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 800, 380));

        jMenu1.setText("Αρχείο");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jMenu1MouseReleased(evt);
            }
        });

        jMenuItem3.setText("Έξοδος");
        jMenuItem3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem3MousePressed(evt);
            }
        });
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        info.setText("Πληροφορίες");
        info.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                infoMousePressed(evt);
            }
        });

        admin.setText("Διαχειριστής");
        admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminMousePressed(evt);
            }
        });
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        info.add(admin);

        jMenuBar1.add(info);

        help.setText("Σχετικά με");
        help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                helpMousePressed(evt);
            }
        });
        jMenuBar1.add(help);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

         
         
         

    private void arrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrowActionPerformed
        dispose();
        home next =new home();
        next.setVisible(true);
    }//GEN-LAST:event_arrowActionPerformed
    private void payActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payActionPerformed
         verify.setVisible(true);
         jLabel9.setVisible(true);
         jButton1.setVisible(true);
         userverify.setVisible(true);
         verify1.setVisible(true);
          pay.setEnabled(false);
    }//GEN-LAST:event_payActionPerformed
        
    private void informationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informationActionPerformed
        dispose();
        info next =new info();
        next.setVisible(true);
    }//GEN-LAST:event_informationActionPerformed

    private void userverifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userverifyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userverifyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String test=String.valueOf(home.table[exit.thesi][0]);
        if (verify1.getText().equals(userverify.getText())){
            response.setText("");
        for (int i=0;i<5;i++){
            if (home.table[exit.thesi][i]!=null){
                home.table[exit.thesi][i]=null;
                if (i<=2){
                    home.time[exit.thesi][i]=Double.NaN;
                }            
            }
        }
        LocalDateTime myDateObj = LocalDateTime.now();
        DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("HH:mm:ss");
        String formattedDate = myDateObj.format(myFormatObj);
        System.out.println("Το όχημα με Αριθμο Κυκλόφωριας : "+test+"\t Βγήκε στις : "+formattedDate);

       
        thankyou.setLocation(450,300);
        thankyou.setVisible(true);
        dispose();
        home next =new home();
        next.setVisible(true);
    }
    else{
        response.setText("Please Try again");
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
        thankyou.setVisible(false);
        
    }//GEN-LAST:event_jButton3MousePressed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        close.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem3MousePressed
        close.setVisible(true);
        close.setLocation(650,400);
    }//GEN-LAST:event_jMenuItem3MousePressed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1MouseReleased

    private void adminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMouseClicked

    }//GEN-LAST:event_adminMouseClicked

    private void adminMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminMousePressed
        dispose();
        admin next =new admin();
        next.setVisible(true);
    }//GEN-LAST:event_adminMousePressed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminActionPerformed

    private void infoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMouseClicked

    }//GEN-LAST:event_infoMouseClicked

    private void infoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoMousePressed

    }//GEN-LAST:event_infoMousePressed

    private void helpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_helpMouseClicked

    private void helpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpMousePressed
        helpdialog.setVisible(true);
        helpdialog.setVisible(true);
        helpdialog.setSize(690,375);
        helpdialog.setLocation(450,300);

    }//GEN-LAST:event_helpMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pliromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pliromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pliromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pliromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pliromi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admin;
    private javax.swing.JLabel akfinded;
    private javax.swing.JButton arrow;
    private javax.swing.JDialog close;
    private javax.swing.JLabel cost;
    private javax.swing.JLabel extra;
    private javax.swing.JMenu help;
    private javax.swing.JDialog helpdialog;
    private javax.swing.JMenu info;
    private javax.swing.JButton information;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JButton pay;
    private javax.swing.JLabel response;
    private javax.swing.JDialog thankyou;
    private javax.swing.JLabel time2;
    private javax.swing.JTextField userverify;
    private javax.swing.JLabel verify;
    private javax.swing.JLabel verify1;
    private javax.swing.JLabel verify12;
    // End of variables declaration//GEN-END:variables
}
